services:
  app:
    build:
      target: deps
    command: bun run dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - PORT:3000
    # Use host network in development too
    network_mode: "host"
